apiVersion: v1
kind: Service 
metadata:
   name: back-expose-service
   namespace: todo-app
spec:
   selector:
      type: back
   type: ClusterIP
   ports:
   -  port: 27017
      targetPort: 27017
      