apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-deployment
  namespace: todo-list
spec:
  selector:
    matchLabels:
      type: back
  template:
    metadata:
      labels:
        type: back
    spec:
      containers:
      - name: back-container
        image: mongo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
