apiVersion: v1
kind: Service
metadata:
  name: front-expose-service
  namespace: todo-app
spec:
  selector:
    type: front
  type: NodePort
  ports:
  -    port: 9000
       targetPort: 9000
       nodePort: 31900
