apiVersion: v1

kind: PersistantVolume

metadata:
  name: todo-data-storage
  namespace: todo-app

spec:
  capacity:
    storage: 5Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistantVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node